In [1]:
import sys
sys.path.append('../')
import corecomposition as cc

import numpy as np
import pyvo as vo
import matplotlib.pyplot as plt
from astropy.table import Table, join

In [2]:
gold = Table.read('../data/gold.csv')
silver = Table.read('../data/silver.csv')
bronze = Table.read('../data/bronze.csv')

In [3]:
photo = cc.photometry.fetch_photometry(bronze['wd_source_id'])
bronze = join(bronze, photo, keys_left='wd_source_id', keys_right='source_id')


In [4]:
photo[photo['source_id'] == 1307515077152381568]

<Table length=1>
     source_id       PS1_g   PS1_r   PS1_i  ... e_PS1_y source qualityFlag
                      mag     mag     mag   ...   mag                     
       int64        float32 float32 float32 ... float32  str3     uint8   
------------------- ------- ------- ------- ... ------- ------ -----------
1307515077152381568 20.4947 20.3694 20.0103 ...  -999.0    ps1          53

In [5]:
source_ids = bronze['wd_source_id']
distances = bronze['distance']
astrometric_params = bronze['wd_astrometric_params_solved']
photo = np.array([bronze['wd_phot_g_mean_mag'], bronze['wd_phot_bp_mean_mag'], bronze['wd_phot_rp_mean_mag']]).T
e_photo = np.array([bronze['wd_e_gmag'], bronze['wd_e_bpmag'], bronze['wd_e_rpmag']]).T
initial_params = np.array([bronze['CO_Hdef_teff'], bronze['CO_Hdef_radius']]).T

In [6]:
photo[0]

array([20.463974  , 20.26536369, 20.02454376])

In [7]:
i = 0
obj = cc.photometry.Photometry(source_ids, distances, astrometric_params, photo, e_photo, initial_params)

In [8]:
obj.photo[1307515077152381568]

[191.31002807617188,
 31,
 array(['Gaia_G', 'Gaia_BP', 'Gaia_RP', 'PS1_g', 'PS1_r', 'PS1_i', 'PS1_z',
        'PS1_y'], dtype='<U7'),
 array([  20.463974  ,   20.26536369,   20.02454376,   20.49469948,
          20.36940002,   20.01029968,   19.78759956, -999.        ]),
 array([ 4.66615165e-03,  1.41416389e-01,  9.53912634e-02,  2.62470003e-02,
         3.36810015e-02,  4.40989994e-02,  1.08457997e-01, -9.99000000e+02]),
 array([8.89800454e+03, 7.23204103e-03])]

In [9]:
obj.run_mcmc(cc.interpolator.LaPlataBase, layer='Hrich')

TypeError: Photometry.run_mcmc() missing 1 required positional argument: 'initial_params'

In [ ]:
gold_coverage = join(gold, table, keys_left='wd_source_id', keys_right='source_id')
silver_coverage = join(silver, table, keys_left='wd_source_id', keys_right='source_id')
bronze_coverage = table

print(f'gold coverage = {len(gold_coverage)} / {len(gold)}')
print(f'silver coverage = {len(silver_coverage)} / {len(silver)}')
print(f'bronze coverage = {len(bronze_coverage)} / {len(bronze)}')

NameError: name 'table' is not defined

In [ ]:
gold_coverage

<Table length=3>
   wd_solution_id      ms_solution_id   ... mag_auto_z mag_auto_y
                                        ...    mag        mag    
       int64               int64        ...  float32    float32  
------------------- ------------------- ... ---------- ----------
1636042515805110273 1636042515805110273 ...         --         --
1636042515805110273 1636042515805110273 ...         --         --
1636042515805110273 1636042515805110273 ...         --         --